CREATE TABLE AccessLevels (
    AccessLevelID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, -- Unikalne ID poziomu dostępu
    AccessLevelName VARCHAR2(50) NOT NULL,                             -- Nazwa poziomu dostępu (np. "Top Secret", "Restricted")
    Description VARCHAR2(255)                                          -- Opis poziomu dostępu
);