name: Run API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Check if .env file exists
      run: |
        if [ ! -f .env ]; then
          echo ".env file not found"
          exit 1
        fi
        echo ".env file found, loading variables"

    - name: Load environment variables from .env file
      run: |
        cat .env | grep -v '#' | xargs -I {} echo {} >> $GITHUB_ENV

    - name: Debug environment variables
      run: env | grep MOCK_API || echo "No MOCK_API variables found"

    - name: Run API tests from runTests.js
      run: node runTests.js
