name: Run API and SQL Tests # Nazwa workflow

on: # Zdarzenia uruchamiające workflow
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Load environment variables
        run: |
          echo "MOCK_API_URL=${{ secrets.MOCK_API_URL }}" >> $GITHUB_ENV
          echo "MOCK_API_BALANCE_PATH=${{ secrets.MOCK_API_BALANCE_PATH }}" >> $GITHUB_ENV
          echo "MOCK_API_TRANSACTIONS_PATH=${{ secrets.MOCK_API_TRANSACTIONS_PATH }}" >> $GITHUB_ENV
          echo "LOGIN_API_URL=${{ secrets.LOGIN_API_URL }}" >> $GITHUB_ENV
          echo "LOGIN_API_LOGIN_PATH=${{ secrets.LOGIN_API_LOGIN_PATH }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> $GITHUB_ENV

      - name: Wait for MySQL to initialize
        run: |
          while ! mysqladmin ping -h"127.0.0.1" --silent; do
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Define SQL base path and test files
        run: |
          echo "SQL_TEST_PATH='sql-tests/tests'" >> $GITHUB_ENV
          echo "SQL_TEST_FILES='
            add_permission_test.sql
            users_table_test.sql
            users_activity_test.sql
            login_and_password_test.sql
            pucharse_test.sql
            leaderboard_test.sql
          '" >> $GITHUB_ENV

      - name: Run SQL Tests
        env:
          MYSQL_PWD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: |
          for file in $SQL_TEST_FILES; do
            echo "Executing $SQL_TEST_PATH/$file..."
            mysql -h 127.0.0.1 -u root -D ${{ secrets.MYSQL_DATABASE }} < "$SQL_TEST_PATH/$file"
          done
