name: Run API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    # Nowy krok: Załaduj zmienne środowiskowe z pliku .env
    - name: Load environment variables from .env file
      run: |
        if [ -f .env ]; then
          echo "Loading environment variables from .env file"
          export $(cat .env | xargs)
        fi

    # Alternatywa, jeśli chcesz używać GitHub Secrets zamiast pliku .env
    # - name: Load environment variables
    #   run: |
    #     echo "MOCK_API_URL=${{ secrets.MOCK_API_URL }}" >> $GITHUB_ENV
    #     echo "MOCK_API_BALANCE_PATH=${{ secrets.MOCK_API_BALANCE_PATH }}" >> $GITHUB_ENV
    #     echo "MOCK_API_TRANSACTIONS_PATH=${{ secrets.MOCK_API_TRANSACTIONS_PATH }}" >> $GITHUB_ENV
    #     echo "LOGIN_API_URL=${{ secrets.LOGIN_API_URL }}" >> $GITHUB_ENV
    #     echo "LOGIN_API_LOGIN_PATH=${{ secrets.LOGIN_API_LOGIN_PATH }}" >> $GITHUB_ENV

    - name: Run API tests from runTests.js
      run: node runTests.js
