name: Run API and SQL Tests # Nazwa workflow

on: # Zdarzenia uruchamiające workflow
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql: # Dodanie usługi MySQL
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}  # Hasło dla root
          MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}  # Baza danych, którą używasz
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Load environment variables
        run: |
          echo "MOCK_API_URL=${{ secrets.MOCK_API_URL }}" >> $GITHUB_ENV
          echo "MOCK_API_BALANCE_PATH=${{ secrets.MOCK_API_BALANCE_PATH }}" >> $GITHUB_ENV
          echo "MOCK_API_TRANSACTIONS_PATH=${{ secrets.MOCK_API_TRANSACTIONS_PATH }}" >> $GITHUB_ENV
          echo "LOGIN_API_URL=${{ secrets.LOGIN_API_URL }}" >> $GITHUB_ENV
          echo "LOGIN_API_LOGIN_PATH=${{ secrets.LOGIN_API_LOGIN_PATH }}" >> $GITHUB_ENV
          echo "DB_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}" >> $GITHUB_ENV # Pobranie hasła z pliku .env

      - name: Run API tests from folder
        run: npm run test:folder

      - name: Run login API tests
        run: npm run test:login

      - name: Wait for MySQL to initialize
        run: |
          while ! mysqladmin ping -h"127.0.0.1" --silent; do
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Run SQL Tests
        env:
          MYSQL_PWD: ${{ secrets.MYSQL_ROOT_PASSWORD }} # Hasło root z secrets
        run: |
          mysql -h 127.0.0.1 -u root -p${{ secrets.MYSQL_ROOT_PASSWORD }} -D ${{ secrets.MYSQL_DATABASE }} < sql-tests/tests/add_permission_test.sql
      
