name: Run API Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Load environment variables from .env file
      run: |
        if [ -f .env ]; then
          echo "Loading environment variables from .env file"
          cat .env | grep -v '#' | xargs -I {} echo {} >> $GITHUB_ENV
        fi

    - name: Debug environment variables
      run: env | grep MOCK_API

    - name: Run API tests from runTests.js
      run: node runTests.js
